### ISSUE TITLE
[R-CNN] : [ridge regression]

### ISSUE THREAD

**Issue by ownvoy** [devkade/DeepSync#12]
# question
ridgeregression이 뭔가요?

![image](https://github.com/mouseku/DeepSync/assets/96481582/de94f526-c259-470c-a57d-c5838c9aac09)

# answer

---
add the assignees

**Comment by ownvoy** [comment]
$\hat{w}$가 너무 커지지 않는 방식으로 정규화 합니다.

cf)
Ridge regression: L2 Regularization을 사용하는 선형회귀 모델
Lasso regression: L1 Regularization을 사용하는 선형회귀 모델

**Comment by devkade** [comment]
어떻게 $\hat w$ 가 커지지 않나요?

**Comment by ownvoy** [comment]
regulation이 없는 식은 아래와 같습니다.
$$\hat{w} = \underset{\hat{w}}{\mathrm{argmin}}{\overset{N}{\underset{i}{\sum}}}(t^{i} -\hat{w}^{T}\phi_{5}(P^{i}))^2$$

다만 이렇게 되면, $\hat{w}$가 커지는 방향으로 학습이 될 수 있습니다. 
뒤에 $\lambda||\hat{w}||^{2}$ 항을 추가하면서, argmin은 $(t^{i} -\hat{w}^{T}\phi_{5}(P^{i}))$이 최소화 되는 동시에, $\hat{w}$ 역시 최소화 하는 식으로  학습하게 됩니다. 

$\lambda$는 hyper parameter로, 이 값이 클수록 더 강한 정규화가 됩니다.
