### ISSUE TITLE
[Fast R-CNN] : [caching]

### ISSUE THREAD

**Issue by ownvoy** [devkade/DeepSync#13]
# question
질문자: @ownvoy 
1. 왜 Fast R-CNN은 caching을 위한 공간이 필요하지 않나요?
2. 그럼 이전 모델 R-CNN은 caching을 위한 공간이 필요하나요?
![image](https://github.com/mouseku/DeepSync/assets/96481582/1ac05204-8477-449e-9543-244f43f0db1d)

# answer

**Comment by mouseku** [comment]
R-CNN과 SPPnet은 CNN을 통과한 특징맵을 저장합니다. 

R-CNN은 특징맵을 저장하여 SS로 찾아낸 RoI가 서로 겹치는 경우 가중치를 공유(재사용)할 수 있어, 계산적 측면에서 이득을 얻기 위함입니다. 

SPPnet에서의 caching은 전체 이미지에 대한 CNN 특징맵을 caching하고, RoI에 대해 특징 추출을 할 때 반복해서 특징맵을 활용하는 것을 말합니다. 

Fast R-CNN에서도 SPPnet과 동일하게 특징맵을 RoI에 대해 여러 번 반복해서 사용한다는 관점에서는 caching을 한다고 말할 수 있습니다. 하지만, R-CNN의 관점과 같이 RoI A, RoI B에 대해 각각 특징맵 A, 특징맵 B를 저장할 필요없이 하나의 특징맵만 사용합니다. 

저는 논문에서 말한 feature caching을 하기 위한 디스크가 필요하지 않다는 것은 R-CNN에서의 관점으로 다룬 것으로 이해했습니다.

+발표에서 말씀드렸던 caching이 SVM으로 인해 발생한다는 점은 잘못된 정보입니다. 발표 시 올바른 정보만 전달할 수 있도록 하겠습니다:)
