### ISSUE TITLE
[Fast R-CNN] : [SVM 학습]

### ISSUE THREAD

**Issue by ownvoy** [devkade/DeepSync#14]
# question

질문자: @naboyeong
SVM이 학습이 안되어서, Fast R-CNN은 softmax를 통한 Multi-task loss를 사용했다고 한다.
근데 SVM은 학습이 안 되는가? SVM 또한 학습이 되는 것으로 알 수 있다.

# answer

**Comment by mouseku** [comment]
관련해서 검색하고 고민해본 결과 SVM 대신 Softmax를 사용한 이유는 다음과 같습니다.

### SVM과 Softmax의 차이
1. SVM은 이진 분류 기법인 반면, Softmax는 다중 분류를 한다.  
2. SVM의 학습은 특징의 학습이 아닌, 최적의 분리 초평면을 조정하는 학습이다. 즉, 입력이 주어졌을 때 주어진 입력을 분리하는 초평면을 찾기 위해 조정하는 학습이다.
3. Softmax의 경우 fc layer를 통해 찾아낸 새로운 특징 공간에서의 값을 통해 분류한다. SVM은 본질적으로 어떤 특징공간을 학습하여 분류를 하는 것이 아닌, 주어진 입력에 대해 분리하는 역할만 한다. (커널 함수를 설정해 비선형 분류를 할 수 있으나, 이 또한 특징 공간을 학습 하는 것은 아닙니다.)


### SVM 대신 Softmax를 사용한 이유
- 학습의 통일성 (End-to-End Training) 
Fast R-CNN은 네트워크를 통해 전체적으로 연결되어 있습니다. 전체적으로 연결되어 있다는 것은 하나의 손실 함수를 통해 전체 layer가 학습될 수 있어, 분류기를 학습을 통해 조정하면 특징 추출기도 함께 학습이 된다는 것을 의미합니다. 즉, 마지막 fc layer를 통해서 분류를 잘 할 수 있는 특징 공간을 학습하고, softmax를 통해 결과를 도출한다는 의미입니다.
하지만 SVM의 경우 위에서 설명한 것과 같이 특징을 학습하지는 않습니다. 때문에 SVM을 사용한 경우 CNN을 통해 특징을 추출하는 부분과 SVM에 추출한 특징을 입력해 분류하는 부분, 두 부분이 연결되지 않고 별개의 stage로 나눠집니다. 때문에 End-to-End 학습을 할 수 없게 됩니다. 

정리하자면 Softmax의 경우 내가 잘 분류하기 위한 특징 공간 A가 있다고 하면 특징 공간을 A로 만들기 위한 정보를 fc layer로 전달해줄 수 있으나, SVM의 경우 별도의 stage로 나누어져 A로 만들기 위한 정보를 전달해 줄 수 없습니다. 때문에 Fast R-CNN의 경우 softmax를 사용함으로써 SVM을 사용한 것보다 더 방향성이 명확한 정보를 습득한다고 생각할 수 있습니다.
